name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
<<<<<<< HEAD
  workflow_dispatch:
=======
>>>>>>> a5e5794 (updated the files to make the github action run correctly)

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
=======
    env:
      SECRET_KEY: "test_secret"   # Provide SECRET_KEY for CI
      ALGORITHM: "HS256"          # Optional, just in case
>>>>>>> a5e5794 (updated the files to make the github action run correctly)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          cd saas_billing_API
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx pymongo

      - name: Run tests
        run: |
          cd saas_billing_API
          pytest -v
