name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017

    env:
      SECRET_KEY: "test_secret"   # Provide SECRET_KEY for CI
      ALGORITHM: "HS256"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r saas_billing_API/requirements.txt
          pip install pytest pytest-asyncio httpx pymongo

      - name: Run tests
        run: |
          pytest -v saas_billing_API/tests
