name: FastAPI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    # Start MongoDB service
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: --bind_ip_all

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017
          DB_NAME: saas_billing_test
        run: |
          pytest -v
